from discord import Colour

blue = Colour.from_str("#0d6efd")
indigo = Colour.from_str("#6610f2")
purple = Colour.from_str("#6f42c1")
pink = Colour.from_str("#d63384")
red = Colour.from_str("#dc3545")
orange = Colour.from_str("#fd7e14")
yellow = Colour.from_str("#ffc107")
green = Colour.from_str("#198754")
teal = Colour.from_str("#20c997")
cyan = Colour.from_str("#0dcaf0")
black = Colour.from_str("#000")
white = Colour.from_str("#fff")
gray = Colour.from_str("#6c757d")
